theme = "PaperMod"
baseURL = "https://innovationwizard.github.io/journalmarcel/"
publishDir = "docs"
title = 'Journal Marcel'

[params.assets]
  favicon = "/static/favicon.ico"
  favicon16x16 = "/static/favicon-16x16.png"
  favicon32x32 = "/static/favicon-32x32.png"
  apple_touch_icon = "/static/apple-touch-icon.png"
  safari_pinned_tab = "/static/safari-pinned-tab.svg"
  theme_color = "#2e2e33"
  msapplication_TileColor = "#2e2e33"
